[package]
name = "witty"
version = "0.1.0"
authors = ["Stanko Krtalić <stanko.krtalic@gmail.com>"]

[dependencies]
hyper = "0.10.4"
hyper-native-tls = "0.2.2"
serde = "0.9.7"
serde_json = "0.9.6"
serde_derive = "0.9.7"
serde_urlencoded = "0.4.2"
